package br.bmcopias.util;

/**
 *
 * @author Alex Simas Braz
 *
 */
public enum IconeEnum {

	ACTION_BACK("action_back",".gif"),
	action_forward("action_forward",".gif"),
	action_go("action_go",".gif"),
	action_paste("action_paste",".gif"),
	action_print("action_print",".gif"),
	action_refresh("action_refresh",".gif"),
	action_refresh_blue("action_refresh_blue",".gif"),
	action_save("action_save",".gif"),
	action_stop("action_stop",".gif"),
	application_dreamweaver("application_dreamweaver",".gif"),
	application_firefox("application_firefox",".gif"),
	application_flash("application_flash",".gif"),
	arrow_down("arrow_down",".gif"),
	arrow_left("arrow_left",".gif"),
	arrow_right("arrow_right",".gif"),
	arrow_up("arrow_up",".gif"),
	botao_check1("botao_check1",".gif"),
	botao_check2("botao_check2",".gif"),
	botao_check3("botao_check3",".gif"),
	botao_info("botao_info",".gif"),
	botao_info2("botao_info2",".gif"),
	botao_info3("botao_info3",".gif"),
	botao_info_quad1("botao_info_quad1",".gif"),
	botao_info_quad2("botao_info_quad2",".gif"),
	botao_info_quad3("botao_info_quad3",".gif"),
	box("box",".gif"),
	bt_fav("bt_fav",".gif"),
	bt_hoje("bt_hoje",".gif"),
	bt_nav5("bt_nav5",".gif"),
	bt_nav6("bt_nav6",".gif"),
	bt_nav7("bt_nav7",".gif"),
	calendar("calendar",".gif"),
	canto_direito("canto_direito",".gif"),
	canto_esquerdo("canto_esquerdo",".gif"),
	chmod("chmod",".gif"),
	comment("comment",".gif"),
	comment_blue("comment_blue",".gif"),
	comment_delete("comment_delete",".gif"),
	comment_new("comment_new",".gif"),
	comment_yellow("comment_yellow",".gif"),
	consulta1("consulta1",".gif"),
	CONTINUE("continue",".gif"),
	coordenador("coordenador",".gif"),
	copy("copy",".gif"),
	copy_d("copy_d",".gif"),
	copy_f("copy_f",".gif"),
	copy_l_co("copy_l_co",".gif"),
	copy_r_co("copy_r_co",".gif"),
	cut("cut",".gif"),
	date("date",".gif"),
	date_delete("date_delete",".gif"),
	date_new("date_new",".gif"),
	delete("delete",".gif"),
	desativar("desativar",".gif"),
	drop_yes("drop-yes",".gif"),
	edit("edit",".gif"),
	excluir("excluir",".gif"),
	faturamento("faturamento",".gif"),
	file_acrobat("file_acrobat",".gif"),
	file_font("file_font",".gif"),
	file_font_truetype("file_font_truetype",".gif"),
	filtro("filtro",".gif"),
	flag1("flag1",".gif"),
	flag2("flag2",".gif"),
	flag3("flag3",".gif"),
	flag4("flag4",".gif"),
	flag_blue("flag_blue",".gif"),
	flag_green("flag_green",".gif"),
	flag_orange("flag_orange",".gif"),
	flag_red("flag_red",".gif"),
	flag_white("flag_white",".gif"),
	folder("folder",".gif"),
	folder_delete("folder_delete",".gif"),
	folder_images("folder_images",".gif"),
	folder_lock("folder_lock",".gif"),
	folder_new("folder_new",".gif"),
	folder_page("folder_page",".gif"),
	Forward16("Forward16",".gif"),
	Forward24("Forward24",".gif"),
	fundo5("fundo5",".gif"),
	go_button("go_button",".gif"),
	grid_loading("grid-loading",".gif"),
	hmenu_asc("hmenu-asc",".gif"),
	hmenu_desc("hmenu-desc",".gif"),
	hmenu_lock("hmenu-lock",".gif"),
	hmenu_unlock("hmenu-unlock",".gif"),
	home("home",".gif"),
	htpasswd("htpasswd",".gif"),
	icon_accept("icon_accept",".gif"),
	icon_airmail("icon_airmail",".gif"),
	icon_alert("icon_alert",".gif"),
	icon_attachment("icon_attachment",".gif"),
	icon_clock("icon_clock",".gif"),
	icon_component("icon_component",".gif"),
	icon_download("icon_download",".gif"),
	icon_email("icon_email",".gif"),
	icon_extension("icon_extension",".gif"),
	icon_favourites("icon_favourites",".gif"),
	icon_get_world("icon_get_world",".gif"),
	icon_history("icon_history",".gif"),
	icon_home("icon_home",".gif"),
	icon_info("icon_info",".gif"),
	icon_key("icon_key",".gif"),
	icon_link("icon_link",".gif"),
	icon_mail("icon_mail",".gif"),
	icon_monitor_mac("icon_monitor_mac",".gif"),
	icon_monitor_pc("icon_monitor_pc",".gif"),
	icon_network("icon_network",".gif"),
	icon_package("icon_package",".gif"),
	icon_package_get("icon_package_get",".gif"),
	icon_package_open("icon_package_open",".gif"),
	icon_padlock("icon_padlock",".gif"),
	icon_security("icon_security",".gif"),
	icon_settings("icon_settings",".gif"),
	icon_user("icon_user",".gif"),
	icon_wand("icon_wand",".gif"),
	icon_world("icon_world",".gif"),
	icon_world_dynamic("icon_world_dynamic",".gif"),
	image("image",".gif"),
	image_new("image_new",".gif"),
	im_Calendario("im_Calendario",".gif"),
	inserted("inserted",".gif"),
	interface_browser("interface_browser",".gif"),
	interface_dialog("interface_dialog",".gif"),
	interface_installer("interface_installer",".gif"),
	list_comments("list_comments",".gif"),
	list_components("list_components",".gif"),
	list_errors("list_errors",".gif"),
	list_extensions("list_extensions",".gif"),
	list_images("list_images",".gif"),
	list_keys("list_keys",".gif"),
	list_links("list_links",".gif"),
	list_packages("list_packages",".gif"),
	list_security("list_security",".gif"),
	list_settings("list_settings",".gif"),
	list_users("list_users",".gif"),
	list_world("list_world",".gif"),
	lixeira("lixeira",".gif"),
	loading("loading",".gif"),
	logout("logout",".gif"),
	lupa("lupa",".gif"),
	marcador_menuVertical("marcador_menuVertical",".gif"),
	mnuEditCopy("mnuEditCopy",".gif"),
	mnuEditCut("mnuEditCut",".gif"),
	mnuEditDelete("mnuEditDelete",".gif"),
	mnuEditPaste("mnuEditPaste",".gif"),
	mnuFileExit("mnuFileExit",".gif"),
	mnuFileExport("mnuFileExport",".gif"),
	mnuFileNew("mnuFileNew",".gif"),
	mnuFileOpen("mnuFileOpen",".gif"),
	mnuFileSave("mnuFileSave",".gif"),
	mnuViewZoom("mnuViewZoom",".gif"),
	move_d("move_d",".gif"),
	move_f("move_f",".gif"),
	navback("navback",".gif"),
	navfore("navfore",".gif"),
	navup("navup",".gif"),
	note("note",".gif"),
	note_delete("note_delete",".gif"),
	note_new("note_new",".gif"),
	nowait("nowait",".gif"),
	page_first_disabled("page-first-disabled",".gif"),
	page_first("page-first",".gif"),
	page_last_disabled("page-last-disabled",".gif"),
	page_last("page-last",".gif"),
	page_next_disabled("page-next-disabled",".gif"),
	page_next2("page-next",".gif"),
	page_prev_disabled("page-prev-disabled",".gif"),
	page_prev2("page-prev",".gif"),
	page("page",".gif"),
	page_alert("page_alert",".gif"),
	page_attachment("page_attachment",".gif"),
	page_bookmark("page_bookmark",".gif"),
	page_boy("page_boy",".gif"),
	page_code("page_code",".gif"),
	page_colors("page_colors",".gif"),
	page_component("page_component",".gif"),
	page_cross("page_cross",".gif"),
	page_delete("page_delete",".gif"),
	page_deny("page_deny",".gif"),
	page_down("page_down",".gif"),
	page_dynamic("page_dynamic",".gif"),
	page_edit("page_edit",".gif"),
	page_extension("page_extension",".gif"),
	page_favourites("page_favourites",".gif"),
	page_find("page_find",".gif"),
	page_flash("page_flash",".gif"),
	page_girl("page_girl",".gif"),
	page_html("page_html",".gif"),
	page_java("page_java",".gif"),
	JAVA("java",".png"),
	page_key("page_key",".gif"),
	page_left("page_left",".gif"),
	page_link("page_link",".gif"),
	page_lock("page_lock",".gif"),
	page_new("page_new",".gif"),
	page_next("page_next",".gif"),
	page_package("page_package",".gif"),
	page_php("page_php",".gif"),
	page_prev("page_prev",".gif"),
	page_refresh("page_refresh",".gif"),
	page_right("page_right",".gif"),
	page_script("page_script",".gif"),
	page_security("page_security",".gif"),
	page_settings("page_settings",".gif"),
	page_sound("page_sound",".gif"),
	page_tag_blue("page_tag_blue",".gif"),
	page_tag_red("page_tag_red",".gif"),
	page_text("page_text",".gif"),
	page_text_delete("page_text_delete",".gif"),
	page_tick("page_tick",".gif"),
	page_tree("page_tree",".gif"),
	page_up("page_up",".gif"),
	page_url("page_url",".gif"),
	page_user("page_user",".gif"),
	page_user_dark("page_user_dark",".gif"),
	page_user_light("page_user_light",".gif"),
	page_video("page_video",".gif"),
	page_wizard("page_wizard",".gif"),
	password("password",".gif"),
	pick_button("pick-button",".gif"),
	prev("prev",".gif"),
	refresh18("refresh18",".gif"),
	refresh24("refresh24",".gif"),
	reloadhtml("reloadhtml",".gif"),
	rename("rename",".gif"),
	ResumoPedidos("ResumoPedidos",".gif"),
	save("save",".gif"),
	save24("save24",".gif"),
	SaveAll16("SaveAll16",".gif"),
	sort_asc("sort_asc",".gif"),
	sort_desc("sort_desc",".gif"),
	space("space",".gif"),
	sql("sql",".gif"),
	StatusDown_B("StatusDown_B",".gif"),
	std("std",".gif"),
	steam("steam",".gif"),
	table("table",".gif"),
	tables("tables",".gif"),
	table_delete("table_delete",".gif"),
	text("text",".gif"),
	text_html("text.html",".gif"),
	text_plain("text.plain",".gif"),
	text_rtf("text.rtf",".gif"),
	treeview("treeview-loading",".gif"),
	Undo16("Undo16",".gif"),
	Undo24("Undo24",".gif"),
	user("user",".gif"),
	VtmCaution("VtmCaution",".gif"),
	wait("wait",".gif"),
	WARNING("WARNING",".gif"),
	ZMais("ZMais",".gif"),
	ZMenos("ZMenos",".gif"), 
	boX1("box1", ".bmp")
	;

	private IconeEnum(String nome, String extensao){
		this.nomeIcone = nome;
		this.extensaoIcone = extensao;
	}
	
	public String getNomeCompleto(){
		return nomeIcone + extensaoIcone;
	}

	private String nomeIcone;
	private String extensaoIcone;

	public String getExtensaoIcone() {
		return extensaoIcone;
	}

	public void setExtensaoIcone(String extensaoIcone) {
		this.extensaoIcone = extensaoIcone;
	}

	public String getNomeIcone() {
		return nomeIcone;
	}

	public void setNomeIcone(String nomeIcone) {
		this.nomeIcone = nomeIcone;
	}



}
